seat_yourself/config/routes.rb
SeatYourself::Application.routes.draw do

  root 'restaurants#index'

  resources :restaurants do
    resources :reservations
  end
  resources :users, except: :index
  resources :sessions, only: [:new, :create, :destroy]

  

end

seat_yourself/app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user

	validate :in_the_future

	validates :spot, presence: true
	validates :size, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2, less_than_or_equal_to: 20 }

	private
	def in_the_future
    if spot < (DateTime.now - 1)
      errors.add(:spot, "We haven't invented time travel yet!")
    end
	end
end

seat_yourself/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, through: :reservations
end

seat_yourself/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :name

  has_many :reservations
  has_many :restaurants, through: :reservations
end

seat_yourself/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

seat_yourself/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant
  before_filter :ensure_logged_in

  def index
    @reservation = @restaurant.reservations
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user_id = current_user.id

    if @reservation.save
      redirect_to @restaurant, notice: 'Reservation created successfully!'
    else
      redirect_to @restaurant, notice: 'Reservation unsuccessful!'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to restaurant_reservations_path
  end

  private

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reservation_params
    params.require(:reservation).permit(:spot, :size, :restaurant_id)
  end
end

seat_yourself/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_filter :get_restaurant, :only => [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private
  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address, :cuisine, :url)
  end
end

seat_yourself/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, :notice => "Logged out!"
  end
end

seat_yourself/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :get_user, :only => [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to restaurants_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to restaurants_url
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

seat_yourself/app/helpers/application_helper.rb
module ApplicationHelper
end

seat_yourself/app/helpers/reservations_helper.rb
module ReservationsHelper
end

seat_yourself/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

seat_yourself/app/helpers/sessions_helper.rb
module SessionsHelper
end

seat_yourself/app/helpers/users_helper.rb
module UsersHelper
end

seat_yourself/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

<%= yield %>

  <p>
    <% if current_user %>
      Signed in as <%=link_to current_user.name, current_user %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
    <% end %>
  </p>

</body>
</html>

seat_yourself/app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :spot %>
      <%= f.datetime_select(:spot, minute_step: 60, ampm: true, start_hour: 11, end_hour: 23, start_year: DateTime.now.year) %>
    </div>
    <div class="field">
      <%= f.label :size %>
      <%= f.select(:size, (2..20)) %> 
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

seat_yourself/app/views/reservations/index.html.erb
<%= link_to "Back", @restaurant %>

<h3>Reservations</h3>

  <% @restaurant.reservations.each do |reservation| %>
    <p>
      <li>Time: <%= reservation.spot %></li>
      <li>Party Size: <%= reservation.size %></li>
      <% if reservation.user != nil %>
        <li>Name: <%= reservation.user.name %></li>
      <% end %>
      <%= link_to "Delete", restaurant_reservation_path(@restaurant, reservation), :confirm => "Are you sure you want to delete this reservation?", :method => :delete %>
    </p>
  <% end %>

seat_yourself/app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :cuisine %>
    <%= f.select :cuisine, ["Canadian", "Greek", "Indian", "Italian", "Mexican"] %>

    <%= f.label :url %>
    <%= f.text_field :url %>

    <%= f.submit %>
<% end %>

seat_yourself/app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

seat_yourself/app/views/restaurants/index.html.erb
<h3>Welcome!</h3>
<%= link_to "New restaurant", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
<ul>
	<li> <%= link_to restaurant.name, restaurant %> </li>
	<li> Description: <%= restaurant.description %> </li>
	<li> Address: <%= restaurant.address %> </li>
	<li> Cuisine: <%= restaurant.cuisine %> </li>
	<li> <%= link_to "Official Website", "http://#{restaurant.url}", target: '_blank' %> </li>
</ul>
<% end %>

seat_yourself/app/views/restaurants/new.html.erb
<h1>Add a new restaurant below!</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

seat_yourself/app/views/restaurants/show.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<%= link_to "Delete", @restaurant, :confirm => "Are you sure you want to delete this restaurant?", :method => :delete %>

<li> <%= @restaurant.name %> </li>
<li> Description: <%= @restaurant.description %> </li>
<li> Address: <%= @restaurant.address %> </li>
<li> Cuisine: <%= @restaurant.cuisine %> </li>
<li> <%= link_to "Official Website", "http://#{@restaurant.url}", target: '_blank' %> </li>

<h3><%= link_to "Reservations", restaurant_reservations_path(@restaurant) %></h3>

<% if current_user %>
	<h4>New Reservation</h4>
  <%= render '/reservations/form' %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p> 
<% end %>

seat_yourself/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

seat_yourself/app/views/users/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

seat_yourself/app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to "Already a user? Log in!", new_session_path, class: "link" %>

seat_yourself/app/views/users/show.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>
<%= link_to "Edit", edit_user_path(@user) %>
<%= link_to "Delete", @user, :confirm => "Are you sure you want to delete your account?", :method => :delete %>

<p><%= @user[:name] %></p>
<p><%= @user[:email] %></p>