rainforest/config/routes.rb
Rainforest::Application.routes.draw do
  
  resources :products do
    resources :reviews
    member do
      post 'like'
      post 'unlike'
    end
  end
  
  resources :users, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "/login" => "sessions#new"
  root :to => "users#new"
  

  

end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
	
	has_many :reviews
	# has_many :users, through: :reviews
  has_and_belongs_to_many :users, join_table: "likes"
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates :comment, :presence => true
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :name

  has_many :reviews
  # has_many :products, through: :reviews
  has_and_belongs_to_many :products, join_table: "likes"
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end  
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :get_product, :only => [:show, :edit, :update, :destroy, :like, :unlike]
before_filter :ensure_logged_in, :only => [:like, :unlike]

  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def show
    if current_user
      @review = @product.reviews.build
    end

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html
      format.json { render json: @product } 
    end   
  end

  def create
    @product = Product.create(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end  
  end

  def destroy
    @product.destroy
    
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def like
    @product.users << current_user if !@product.users.include?(current_user)
    redirect_to @product
  end

  def unlike
    @product.users.destroy(current_user)
    redirect_to @product
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def index
    @review = @product.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
        format.js {} # This will look for /views/reviews/create.js.erb
      else
        format.html { render "products/show", notice: 'There was an error.'  }
        format.js {} # This will look for /views/reviews/create.js.erb
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end
end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
layout 'static'

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
layout 'static', :only => [:new, :create]
before_filter :get_user, :only => [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to products_url
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

  <p class="userinfo">
    <% if current_user %>
      Signed in as <%=link_to current_user.name, current_user %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
    <% end %>
  </p>  
</body>
</html>

rainforest/app/views/layouts/static.html.erb
<!DOCTYPE html>
<html class = 'landing-page'>
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag "static" %>
</head>
<body>
	<div id = "container">
		<h1>Welcome to Rainforest. Amazon sucks!<h1>
		<%= yield %>
	</div>
</body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rainforest/app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

rainforest/app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    <% if review.user != nil %>
      <em> by <%= review.user.name %></em>
      Added on: <%= review.created_at %>
    <% end %>
  </p>
<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

rainforest/app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "New product", "/products/new" %>

<% @products.each do |product| %>
<ul>
	<li> <%= link_to product.name, product %> </li>
	<li> Description: <%= product.description %> </li>
	<li> Price: $<%= product.formatted_price %> </li>
</ul>
<% end %>

rainforest/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<div class = "link"> <%= link_to 'Back', products_path %> </div>

rainforest/app/views/products/show.html.erb
<%= link_to "Back to Products", products_url %>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<li><%= @product[:name] %></li>
<li><%= @product[:description] %></li>
<li><%= @product.formatted_price %></li>

<h3><%= link_to "Reviews", product_reviews_path(@product) %></h3>

<div id="review-list">
  <%= render "/products/reviews" %>
</div>

Likes (<%= @product.users.count %>)

<% if current_user %>

<% if @product.users.include?(current_user) %>
  <%= link_to "Unlike", unlike_product_url(@product), method: :unlike %>
<% else %>
  <%= link_to "Like", like_product_url(@product), method: :like %>
<% end %>

  <h4>New Review</h4>

  <%= render '/reviews/form' %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .bind('ajax:beforeSend', function() { # set this code to happen just before the ajax request is made
          $("input[type='submit']") # make changes to the submit button
            .val('Saving...') # change the text on the button
            .attr('disabled', 'disabled'); # disable the button
        })
        .bind('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>

rainforest/app/views/reviews/_form.html.erb
<%= form_for [@product, @review], :remote => true do |f| %>

  <div id="review-form-errors">
    <%= render "/products/review_form_errors" %>
  </div>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rainforest/app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

rainforest/app/views/reviews/index.html.erb
<%= link_to "Back", @product %>

<h3>Reviews</h3>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

rainforest/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>