photogur/config/routes.rb
Photogur::Application.routes.draw do
  resources :pictures
  root :to => "pictures#index"

end

photogur/app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url

  scope :recent, -> { order("updated_at DESC") }
end

photogur/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

photogur/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  before_filter :get_picture, :only => [:show, :edit, :update, :destroy]

  def get_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def create
    # make a new picture with what picture_params returns (which is a method we're calling)
    @picture = Picture.new(picture_params)
    if @picture.save
      # if the save for the picture was successful, go to index.html.erb
      redirect_to pictures_url
    else
      # otherwise render the view associated with the action :new (i.e. new.html.erb)
      render :new
    end
  end

  def edit
  end

  def update
    if @picture.update_attributes(picture_params)
      redirect_to @picture
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path
  end
end

photogur/app/helpers/pictures_helper.rb
module PicturesHelper
end

photogur/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

photogur/app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

photogur/app/views/pictures/index.html.erb
<h1>Pictures</h1>
<%= link_to "New Picture", "/pictures/new" %>

<% Picture.recent.each do |picture| %>
  <p><%= picture[:title] %>, <%= picture[:artist] %></p>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<% end %>

photogur/app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save" %> 
  </p>
<% end %>

photogur/app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %>
<%= link_to "Edit", edit_picture_path(@picture) %>
<%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<%= image_tag @picture.url %>